Added an argument which allows a user to specify which file to load on startup
nimaid/LPHK pull request #66
Opened 2020-09-21 13:01 UTC by kartikay-bagla

I used argparse to replace sys.argv for the debug flag and added another flag `-l --load` in which you can specify any file inside the `user_layouts` folder to load on startup. 

This fixes #65.

2020-09-21 17:49 UTC, duncte123 requested changes
Right now this looks at the default path of the program, this is not where I store my layouts for example.
I suggest adding a check for absolute paths so that layouts can be loaded from all locations

2020-09-22 12:45 UTC, kartikay-bagla commented
I've added the checks for absolute paths as well a check to see whether the file actually exists or not and display a pop-up if the file is not found.

2020-09-27 18:28 UTC, decheine commented
Wow what timing! I've been doing some personal work on that feature for my own version and have it working in my IDE PyCharm. I implemented a config file to determine default layout and possibly other things in the future.

2020-09-28 07:37 UTC, kartikay-bagla commented
> Wow what timing! I've been doing some personal work on that feature for my own version and have it working in my IDE PyCharm. I implemented a config file to determine default layout and possibly other things in the future.

That actually sounds even better than the hack that I made for this.
@duncte123 what do you think? Should we go the config route or the command line argument route.

2020-09-28 07:47 UTC, decheine commented
> > Wow what timing! I've been doing some personal work on that feature for my own version and have it working in my IDE PyCharm. I implemented a config file to determine default layout and possibly other things in the future.
> 
> That actually sounds even better than the hack that I made for this.
> @duncte123 what do you think? Should we go the config route or the command line argument route.

Nice, I'm thinking I might look into other quality of life features and new packages and whatnot, thats what I love about python.

2020-09-28 08:32 UTC, duncte123 commented
I would go the CLI argument route

2020-09-28 22:59 UTC, nimaid commented
> 
> 
> > Wow what timing! I've been doing some personal work on that feature for my own version and have it working in my IDE PyCharm. I implemented a config file to determine default layout and possibly other things in the future.
> 
> That actually sounds even better than the hack that I made for this.
> @duncte123 what do you think? Should we go the config route or the command line argument route.

I agree with @kartikay-bagla, a config file is the better route and the way I planned to implement it before I started focusing on other projects. The plan was to have a "Settings" menu that would allow you to change various things such as default layout, auto-connect override, force launchpad model, etc. This would save to a JSON formatted `LPHK.config` file in the root directory, which is easily modified by hand or other programs.

I like the change to `argparse` for the debug mode, and I'm not opposed to a `--load` CLI flag. However, I do think a config file is the way to go for a "default layout", and the `--load` argument can act as an override to that. In the meantime, I will look over this PR soon.

2020-09-28 23:02 UTC, nimaid commented
One change I definitely think would be good is to use `--layout` instead of `--load`, as it is more clear. Also, a short flag `-l` would be nice.

2020-10-27 15:51 UTC, tsurshor commented
any progress on the feature?
really want to use it

2020-10-27 20:24 UTC, kartikay-bagla commented
@tsurshor you can find a version with this on my GitHub. Though you'll have to run it with python since I don't know how to compile.
@duncte123 hasn't gotten back to me yet after I made the changes.

2020-10-27 21:32 UTC, duncte123 commented
I might be able to look at it this weekend, uni eats all my free time

2020-10-31 14:51 UTC, duncte123 approved these changes
lgtm

2020-11-08 15:11 UTC, tsurshor commented
@kartikay-bagla how would u run it with python?
which file should i run?

2021-03-04 15:12 UTC, duncte123 commented
this was added in #60

2021-03-04 15:12 UTC, closed without merging